[tool.mypy]
python_version = "3.9"
show_column_numbers = true

[tool.isort]
profile = "black"
known_first_party = ["src", "realsense", "microphone", "bltouch"]

[tool.black]
extend-exclude = "/(node_modules|template)/"
